add numpy

In [2]:
import numpy as np

add data set

In [3]:
a = np.genfromtxt('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', dtype=float, delimiter=',', usecols=(0,1,2,3))

checking the table

In [4]:
a.shape

(150, 4)

In [5]:
a.ndim

2

In [6]:
type(a)

numpy.ndarray

create 1 colon

In [7]:
first_column = a[:, 0]
first_column

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

mean 1c

In [8]:
mean_1c = np.mean(first_column)
mean_1c

np.float64(5.843333333333334)

median 1с

In [9]:
median_1с = np.median(first_column)
median_1с

np.float64(5.8)

st_d_1c

In [10]:
st_d_1c = np.std(first_column)
st_d_1c

np.float64(0.8253012917851409)

add 20 NuN to array

In [11]:
n_nan = 20
a[np.unravel_index(np.random.choice(a.size, n_nan, replace=False),a.shape)] = np.nan

a

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, nan],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, nan],
       [4.8, 3.4, 1.9, nan],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, nan, 1.6, 0.2],
       [5.4, 3.4, 1.5, nan],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

find row numbers in the first column containing NaN, first element tuple

In [12]:
nan_ind_a_1c = np.where(np.isnan(a[:,0]))[0]
nan_ind_a_1c

array([ 59,  60,  89, 138])

create filter mask

In [13]:
f_cond = 1.5
s_cond = 5.
mask = ( a[:, 2] > f_cond) & (a[:, 0] < s_cond)
mask


array([False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False,  True, False, False,
       False, False,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

create filter array

In [14]:
filter_a = a[mask]
filter_a

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, nan],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, nan, 1.6, 0.2],
       [4.9, nan, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

change nan to 0.0 in array a

In [15]:
a = np.nan_to_num(a, nan=0.0)
a

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0. ],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0. ],
       [4.8, 3.4, 1.9, 0. ],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 0. , 1.6, 0.2],
       [5.4, 3.4, 1.5, 0. ],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

unique purpose and their number

In [16]:
uniqs, counts =  np.array(np.unique(a, return_counts=True))

result_uniq = np.column_stack((uniqs, counts))
result_uniq

array([[ 0. , 20. ],
       [ 0.1,  6. ],
       [ 0.2, 27. ],
       [ 0.3,  5. ],
       [ 0.4,  6. ],
       [ 0.6,  1. ],
       [ 1. ,  8. ],
       [ 1.1,  3. ],
       [ 1.2,  7. ],
       [ 1.3, 20. ],
       [ 1.4, 20. ],
       [ 1.5, 25. ],
       [ 1.6, 11. ],
       [ 1.7,  6. ],
       [ 1.8, 12. ],
       [ 1.9,  7. ],
       [ 2. ,  7. ],
       [ 2.1,  6. ],
       [ 2.2,  6. ],
       [ 2.3, 11. ],
       [ 2.4,  5. ],
       [ 2.5, 11. ],
       [ 2.6,  5. ],
       [ 2.7,  9. ],
       [ 2.8, 14. ],
       [ 2.9, 10. ],
       [ 3. , 26. ],
       [ 3.1, 11. ],
       [ 3.2, 13. ],
       [ 3.3,  8. ],
       [ 3.4, 12. ],
       [ 3.5,  8. ],
       [ 3.6,  4. ],
       [ 3.7,  4. ],
       [ 3.8,  7. ],
       [ 3.9,  5. ],
       [ 4. ,  6. ],
       [ 4.1,  4. ],
       [ 4.2,  5. ],
       [ 4.3,  3. ],
       [ 4.4,  8. ],
       [ 4.5,  9. ],
       [ 4.6,  7. ],
       [ 4.7,  7. ],
       [ 4.8,  9. ],
       [ 4.9, 11. ],
       [ 5. , 13. ],
       [ 5.1,

splitting an array into two parts

In [17]:
result_split = np.vsplit(a, 2)
result_split

[array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0. ],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0. ],
        [4.8, 3.4, 1.9, 0. ],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 0. , 1.6, 0.2],
        [5.4, 3.4, 1.5, 0. ],
        [5.2, 4.1, 1.5, 0.1],
        [5

sort by increasing

In [18]:
sorted_f_arr = result_split[0][np.argsort(result_split[0][:, 0])]
sorted_f_arr

array([[0. , 2. , 3.5, 1. ],
       [0. , 2.7, 3.9, 1.4],
       [4.3, 3. , 1.1, 0.1],
       [4.4, 2.9, 1.4, 0.2],
       [4.4, 3. , 1.3, 0.2],
       [4.4, 3.2, 1.3, 0.2],
       [4.5, 2.3, 1.3, 0.3],
       [4.6, 3.6, 1. , 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [4.6, 3.4, 1.4, 0. ],
       [4.6, 3.1, 1.5, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0. ],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.8, 0. , 1.6, 0.2],
       [4.8, 3. , 1.4, 0. ],
       [4.9, 3.1, 1.5, 0.1],
       [4.9, 0. , 3.3, 1. ],
       [4.9, 3.1, 1.5, 0.1],
       [4.9, 3. , 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5. , 3.5, 1.6, 0.6],
       [5. , 3.2, 1.2, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5. , 3.5, 1.3, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.1, 3.8, 1.9, 0.4],
       [5.1, 3.4, 1.5, 0.2],
       [5.1, 3.8, 1.6, 0.2],
       [5.1, 3

sort by decreasing

In [19]:
sorted_s_arr = result_split[1][np.argsort(result_split[1][:, 0])[::-1]]
sorted_s_arr

array([[7.9, 3.8, 6.4, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [7.7, 2.6, 6.9, 2.3],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 3. , 6.1, 2.3],
       [7.6, 3. , 6.6, 2.1],
       [7.4, 2.8, 6.1, 1.9],
       [7.3, 2.9, 0. , 1.8],
       [7.2, 3. , 5.8, 1.6],
       [7.2, 3.6, 6.1, 2.5],
       [7.2, 3.2, 6. , 1.8],
       [7.1, 0. , 5.9, 2.1],
       [6.9, 3.1, 5.4, 2.1],
       [6.9, 3.1, 5.1, 2.3],
       [6.9, 3.2, 5.7, 2.3],
       [6.8, 3.2, 5.9, 2.3],
       [6.8, 2.8, 4.8, 1.4],
       [6.8, 3. , 5.5, 2.1],
       [6.7, 3.3, 5.7, 2.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.7, 2.5, 5.8, 1.8],
       [6.7, 3.1, 4.7, 1.5],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 0. , 0. ],
       [6.7, 3. , 5. , 1.7],
       [6.6, 3. , 4.4, 1.4],
       [6.5, 3.2, 5.1, 2. ],
       [6.5, 3. , 0. , 2. ],
       [6.5, 3. , 5.5, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [6.4, 2.8, 5.6, 2.1],
       [6.4, 2.8, 5.6, 2.2],
       [6.4, 3.2, 5.3, 2.3],
       [6.4, 3.1, 5.5, 1.8],
       [6.4, 2

Array concatenation

In [25]:
a_stack = np.vstack([sorted_f_arr, sorted_s_arr])
a_stack

array([[0. , 2. , 3.5, 1. ],
       [0. , 2.7, 3.9, 1.4],
       [4.3, 3. , 1.1, 0.1],
       [4.4, 2.9, 1.4, 0.2],
       [4.4, 3. , 1.3, 0.2],
       [4.4, 3.2, 1.3, 0.2],
       [4.5, 2.3, 1.3, 0.3],
       [4.6, 3.6, 1. , 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [4.6, 3.4, 1.4, 0. ],
       [4.6, 3.1, 1.5, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0. ],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.8, 0. , 1.6, 0.2],
       [4.8, 3. , 1.4, 0. ],
       [4.9, 3.1, 1.5, 0.1],
       [4.9, 0. , 3.3, 1. ],
       [4.9, 3.1, 1.5, 0.1],
       [4.9, 3. , 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5. , 3.5, 1.6, 0.6],
       [5. , 3.2, 1.2, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5. , 3.5, 1.3, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.1, 3.8, 1.9, 0.4],
       [5.1, 3.4, 1.5, 0.2],
       [5.1, 3.8, 1.6, 0.2],
       [5.1, 3

the most repeated value, the probability that there are several of them is taken into account

In [21]:
max_count = np.max(result_uniq[:, 1])
max_value_quantity = result_uniq[result_uniq[:, 1] == max_count]
max_value_quantity

array([[ 0.2, 27. ]])

In [22]:
def meang_processing_fix(arr):
    arr = np.where(arr < np.mean(arr), arr * 2, arr / 4)
    return arr

In [26]:
a_stack[:, 2] = meang_processing_fix(a_stack[:, 2]) 
a_stack

array([[0.   , 2.   , 7.   , 1.   ],
       [0.   , 2.7  , 0.975, 1.4  ],
       [4.3  , 3.   , 2.2  , 0.1  ],
       [4.4  , 2.9  , 2.8  , 0.2  ],
       [4.4  , 3.   , 2.6  , 0.2  ],
       [4.4  , 3.2  , 2.6  , 0.2  ],
       [4.5  , 2.3  , 2.6  , 0.3  ],
       [4.6  , 3.6  , 2.   , 0.2  ],
       [4.6  , 3.2  , 2.8  , 0.2  ],
       [4.6  , 3.4  , 2.8  , 0.   ],
       [4.6  , 3.1  , 3.   , 0.2  ],
       [4.7  , 3.2  , 2.6  , 0.2  ],
       [4.7  , 3.2  , 3.2  , 0.2  ],
       [4.8  , 3.4  , 3.8  , 0.   ],
       [4.8  , 3.4  , 3.2  , 0.2  ],
       [4.8  , 3.   , 2.8  , 0.1  ],
       [4.8  , 0.   , 3.2  , 0.2  ],
       [4.8  , 3.   , 2.8  , 0.   ],
       [4.9  , 3.1  , 3.   , 0.1  ],
       [4.9  , 0.   , 6.6  , 1.   ],
       [4.9  , 3.1  , 3.   , 0.1  ],
       [4.9  , 3.   , 2.8  , 0.2  ],
       [4.9  , 3.1  , 3.   , 0.1  ],
       [5.   , 3.5  , 3.2  , 0.6  ],
       [5.   , 3.2  , 2.4  , 0.2  ],
       [5.   , 3.3  , 2.8  , 0.2  ],
       [5.   , 3.   , 3.2  , 0.2  ],
 